### ISSUE TITLE
not found cornerstonetools-side-image-loader in npm 

### ISSUE THREAD

**Issue by haoxl3** [plantarflex/cornerstoneSideImageLoader#17]
`npm i cornerstonetools-side-image-loader` then I got an error
<img width="894" alt="image" src="https://user-images.githubusercontent.com/15046133/179914623-edf39087-1aca-4b92-a4bd-ea00d919bd76.png">

**Comment by AmrGablla** [comment]
You can use npm i cornerstone-side-image-loader i think they change it and doesn't edit the readme file yet.

**Comment by ZhouXiaolong0** [comment]
> You can use npm i cornerstone-side-image-loader i think they change it and doesn't edit the readme file yet.
hello，when I use this command to install, some error occured, do you know how to install this package now. below is my error.
npm WARN cleanup Failed to remove some directories [
npm WARN cleanup   [
npm WARN cleanup     'D:\\work\\dev\\front-end\\node_modules\\sharp',
npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'D:\work\dev\front-end\node_modules\sharp\vendor\include\freetype2'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'D:\\work\\dev\\front-end\\node_modules\\sharp\\vendor\\include\\freetype2'
npm WARN cleanup     }
npm WARN cleanup   ]
npm WARN cleanup ]
npm ERR! code 1
npm ERR! path D:\work\dev\front-end\node_modules\sharp
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c (node install/libvips && node install/dll-copy && prebuild-install --runtime=napi) || (node-gyp rebuild && node install/dll-copy)
npm ERR! info sharp Using cached C:\Users\A015540\AppData\Local\npm-cache\_libvips\libvips-8.9.1-win32-x64.tar.gz
npm ERR! info sharp Creating D:\work\dev\front-end\node_modules\sharp\build\Release
npm ERR! info sharp Copying DLLs from D:\work\dev\front-end\node_modules\sharp\vendor\lib to D:\work\dev\front-end\node_modules\sharp\build\Release
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.3.1
npm ERR! gyp info using node@18.16.1 | win32 | x64
npm ERR! gyp info find Python using Python version 3.9.13 found at "C:\Users\A015540\AppData\Local\Programs\Python\Python39\python.exe"
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS msvs_version not set from command line or npm config
npm ERR! gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
npm ERR! gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details
npm ERR! gyp ERR! find VS looking for Visual Studio 2015
npm ERR! gyp ERR! find VS - not found
npm ERR! gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS You need to install the latest version of Visual Studio
npm ERR! gyp ERR! find VS including the "Desktop development with C++" workload.
npm ERR! gyp ERR! find VS For more information consult the documentation at:
npm ERR! gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Could not find any Visual Studio installation to use
npm ERR! gyp ERR! stack     at VisualStudioFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:122:47)
npm ERR! gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:75:16
npm ERR! gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:369:14)
npm ERR! gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:71:14
npm ERR! gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:390:16
npm ERR! gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
npm ERR! gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:427:5)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
npm ERR! gyp ERR! System Windows_NT 10.0.19045
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd D:\work\dev\front-end\node_modules\sharp
npm ERR! gyp ERR! node -v v18.16.1
npm ERR! gyp ERR! node-gyp -v v9.3.1
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\A015540\AppData\Local\npm-cache\_logs\2024-03-29T02_32_55_072Z-debug-0.log

**Comment by ZhouXiaolong0** [comment]
> > You can use npm i cornerstone-side-image-loader i think they change it and doesn't edit the readme file yet.
> > hello，when I use this command to install, some error occured, do you know how to install this package now. below is my error.
> > npm WARN cleanup Failed to remove some directories [
> > npm WARN cleanup   [
> > npm WARN cleanup     'D:\work\dev\front-end\node_modules\sharp',
> > npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'D:\work\dev\front-end\node_modules\sharp\vendor\include\freetype2'] {
> > npm WARN cleanup       errno: -4048,
> > npm WARN cleanup       code: 'EPERM',
> > npm WARN cleanup       syscall: 'rmdir',
> > npm WARN cleanup       path: 'D:\work\dev\front-end\node_modules\sharp\vendor\include\freetype2'
> > npm WARN cleanup     }
> > npm WARN cleanup   ]
> > npm WARN cleanup ]
> > npm ERR! code 1
> > npm ERR! path D:\work\dev\front-end\node_modules\sharp
> > npm ERR! command failed
> > npm ERR! command C:\Windows\system32\cmd.exe /d /s /c (node install/libvips && node install/dll-copy && prebuild-install --runtime=napi) || (node-gyp rebuild && node install/dll-copy)
> > npm ERR! info sharp Using cached C:\Users\A015540\AppData\Local\npm-cache_libvips\libvips-8.9.1-win32-x64.tar.gz
> > npm ERR! info sharp Creating D:\work\dev\front-end\node_modules\sharp\build\Release
> > npm ERR! info sharp Copying DLLs from D:\work\dev\front-end\node_modules\sharp\vendor\lib to D:\work\dev\front-end\node_modules\sharp\build\Release
> > npm ERR! gyp info it worked if it ends with ok
> > npm ERR! gyp info using node-gyp@9.3.1
> > npm ERR! gyp info using node@18.16.1 | win32 | x64
> > npm ERR! gyp info find Python using Python version 3.9.13 found at "C:\Users\A015540\AppData\Local\Programs\Python\Python39\python.exe"
> > npm ERR! gyp ERR! find VS
> > npm ERR! gyp ERR! find VS msvs_version not set from command line or npm config
> > npm ERR! gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
> > npm ERR! gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details
> > npm ERR! gyp ERR! find VS looking for Visual Studio 2015
> > npm ERR! gyp ERR! find VS - not found
> > npm ERR! gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
> > npm ERR! gyp ERR! find VS
> > npm ERR! gyp ERR! find VS **************************************************************
> > npm ERR! gyp ERR! find VS You need to install the latest version of Visual Studio
> > npm ERR! gyp ERR! find VS including the "Desktop development with C++" workload.
> > npm ERR! gyp ERR! find VS For more information consult the documentation at:
> > npm ERR! gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
> > npm ERR! gyp ERR! find VS **************************************************************
> > npm ERR! gyp ERR! find VS
> > npm ERR! gyp ERR! configure error
> > npm ERR! gyp ERR! stack Error: Could not find any Visual Studio installation to use
> > npm ERR! gyp ERR! stack     at VisualStudioFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:122:47)
> > npm ERR! gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:75:16
> > npm ERR! gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:369:14)
> > npm ERR! gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:71:14
> > npm ERR! gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:390:16
> > npm ERR! gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
> > npm ERR! gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
> > npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:427:5)
> > npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
> > npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
> > npm ERR! gyp ERR! System Windows_NT 10.0.19045
> > npm ERR! gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
> > npm ERR! gyp ERR! cwd D:\work\dev\front-end\node_modules\sharp
> > npm ERR! gyp ERR! node -v v18.16.1
> > npm ERR! gyp ERR! node-gyp -v v9.3.1
> > npm ERR! gyp ERR! not ok
> 
> npm ERR! A complete log of this run can be found in: npm ERR! C:\Users\A015540\AppData\Local\npm-cache_logs\2024-03-29T02_32_55_072Z-debug-0.log

use npm i cornerstone-side-image-loader --ignore-scripts this command work for me.
